import { pgTable, text, integer, doublePrecision, boolean } from "drizzle-orm/pg-core";

export const parcelleType = pgTable("parcelle_type", {
	id: text("id").primaryKey(),
	communeId: text("commune_id"),
	surface: doublePrecision("surface"),
	numIlotPac: integer("num_ilot_pac"),
	latitude: doublePrecision("latitude"),
	longitude: doublePrecision("longitude"),
	commentaire: text("commentaire"),
	penteMax: text("pente_max"),
	distanceCoursEau: text("distance_cours_eau"),
	bandeEnherbee: text("bande_enherbee"),
	motifFinUtilisation: text("motif_fin_utilisation"),
	dansZonage: text("dans_zonage"),
	commentaireZonage: text("commentaire_zonage"),
	equipementCommentaire: text("equipement_commentaire"),
	systemeIrrigation: boolean("systeme_irrigation"),
	systemeIrrigationType: text("systeme_irrigation_type"),
	pompeType: text("pompe_type"),
	positionnementTuyauxArrosage: text("positionnement_tuyaux_arrosage"),
	eauOrigine: text("eau_origine"),
	systemeFertirrigation: boolean("systeme_fertirrigation"),
	drainage: boolean("drainage"),
	drainageAnneeRealisation: integer("drainage_annee_realisation"),
	protectionAntigel: boolean("protection_antigel"),
	protectionAntigelType: text("protection_antigel_type"),
	protectionAntigrele: boolean("protection_antigrele"),
	protectionAntiinsecte: boolean("protection_antiinsecte"),
	protectionAntipluie: boolean("protection_antipluie"),
	equipementAutre: text("equipement_autre"),
	commentaireSol: text("commentaire_sol"),
	textureSurfaceId: text("texture_surface_id"),
	textureSousSolId: text("texture_sous_sol_id"),
	pierrositeMoyenne: doublePrecision("pierrosite_moyenne"),
	solProfondeurMaxEnracinement: doublePrecision("sol_profondeur_max_enracinement"),
	solProfondeurMaxEnracinementClasse: text("sol_profondeur_max_enracinement_classe"),
	teneurMoPct: doublePrecision("teneur_mo_pct"),
	battance: boolean("battance"),
	ph: doublePrecision("ph"),
	hydromorphie: boolean("hydromorphie"),
	calcaire: boolean("calcaire"),
	proportionCalcaireTotal: doublePrecision("proportion_calcaire_total"),
});

export type ParcelleType = typeof parcelleType.$inferSelect;
export type NewParcelleType = typeof parcelleType.$inferInsert;
