import { pgTable, text, integer, doublePrecision, boolean } from "drizzle-orm/pg-core";

export const domaine = pgTable("domain", {
	id: text("id").primaryKey(),
	code: text("code").notNull(),
	campagne: integer("campagne").notNull(),
	typeFerme: text("type_ferme"),
	departement: text("departement"),
	commune: text("commune"),
	petiteRegionAgricole: text("petite_region_agricole"),
	communeId: text("commune_id"),
	zonage: text("zonage"),
	stationMeteoDefaut: text("station_meteo_defaut"),
	pctSauZoneVulnerable: doublePrecision("pct_sau_zone_vulnerable"),
	pctSauZoneActionsComplementaires: doublePrecision("pct_sau_zone_actions_complementaires"),
	pctSauZoneNatura2000: doublePrecision("pct_sau_zone_natura_2000"),
	pctSauZoneErosion: doublePrecision("pct_sau_zone_erosion"),
	pctSauZoneExcedentStructurel: doublePrecision("pct_sau_zone_excedent_structurel"),
	pctSauPerimetreProtectionCaptage: doublePrecision("pct_sau_perimetre_protection_captage"),
	description: text("description"),
	statutJuridiqueNom: text("statut_juridique_nom"),
	statutJuridiqueCommentaire: text("statut_juridique_commentaire"),
	sauTotale: doublePrecision("sau_totale"),
	culturesCommentaire: text("cultures_commentaire"),
	autresActivitesCommentaire: text("autres_activites_commentaire"),
	moCommentaire: text("mo_commentaire"),
	nombreAssocies: integer("nombre_associes"),
	moFamilialeEtAssocies: doublePrecision("mo_familiale_et_associes"),
	moPermanente: doublePrecision("mo_permanente"),
	moTemporaire: doublePrecision("mo_temporaire"),
	moFamilialeRemuneration: doublePrecision("mo_familiale_remuneration"),
	chargesSalariales: doublePrecision("charges_salariales"),
	moConduiteCulturesDansDomaine: doublePrecision("mo_conduite_cultures_dans_domaine_expe"),
	cotisationMsa: doublePrecision("cotisation_msa"),
	fermagesMoyen: doublePrecision("fermage_moyen"),
	aidesDecouplees: doublePrecision("aides_decouplees"),
	otex18Nom: text("otex_18_nom"),
	otex70Nom: text("otex_70_nom"),
	otexCommentaire: text("otex_commentaire"),
	nombreParcelles: integer("nombre_parcelles"),
	distanceSiegeParcellMax: doublePrecision("distance_siege_parcelle_max"),
	surfaceAutourSiegeExploitation: doublePrecision("surface_autour_siege_exploitation"),
	parcellesGroupees: boolean("parcelles_groupees"),
	parcellesPluTotGroupees: boolean("parcelles_plutot_groupees"),
	parcellesPluTotDispersees: boolean("parcelles_plutot_dispersees"),
	parcellesDispersees: boolean("parcelles_dispersees"),
	parcellesGroupeesDistinctes: boolean("parcelles_groupees_distinctes"),
	objectifs: text("objectifs"),
	atusDomaine: text("atouts_domaine"),
	contraintesDomaine: text("contraintes_domaine"),
	perspectiveEvolutionDomaine: text("perspective_evolution_domaine"),
	membreCooperative: boolean("membre_cooperative"),
	membreGroupeDeveloppement: boolean("membre_groupe_developpement"),
	membreCumul: boolean("membre_cum"),
});

export type Domaine = typeof domaine.$inferSelect;
export type NewDomaine = typeof domaine.$inferInsert;
