import {
	pgTable,
	text,
	integer,
	doublePrecision,
	boolean,
} from "drizzle-orm/pg-core";

export const parcelle = pgTable("parcelle", {
	id: text("id").primaryKey(),
	code: text("code").notNull(),
	campagne: integer("campagne").notNull(),
	pacilotnumber: integer("pacilotnumber"),
	commentaire: text("commentaire"),
	nombreDeZones: integer("nombre_de_zones"),
	equipCommentaire: text("equip_commentaire"),
	surface: doublePrecision("surface"),
	pente: text("pente"),
	distanceCoursEau: text("distance_cours_eau"),
	bandeEnherbee: text("bande_enherbee"),
	dansZonage: text("dans_zonage"),
	commentaireZonage: text("commentaire_zonage"),
	systemeIrrigation: boolean("systeme_irrigation"),
	systemeIrrigationType: text("systeme_irrigation_type"),
	pompeType: text("pompe_type"),
	positionnementTuyauxArrosage: text("positionnement_tuyaux_arrosage"),
	systemeFertirrigation: boolean("systeme_fertirrigation"),
	eauOrigine: text("eau_origine"),
	drainage: boolean("drainage"),
	drainageAnneeRealisation: integer("drainage_annee_realisation"),
	protectionAntigel: boolean("protection_antigel"),
	protectionAntigrele: boolean("protection_antigrele"),
	protectionAntipluie: boolean("protection_antipluie"),
	protectionAntigelType: text("protection_antigel_type"),
	protectionAntiinsecte: boolean("protection_antiinsecte"),
	equipAutre: text("equip_autre"),
	commentaireSol: text("commentaire_sol"),
	textureSurface: text("texture_surface"),
	textureSousSol: text("texture_sous_sol"),
	solNomRef: text("sol_nom_ref"),
	solPh: doublePrecision("sol_ph"),
	solPierrositeMoyenne: doublePrecision("sol_pierrosite_moyenne"),
	solProfondeurMaxEnracinementClasse: text(
		"sol_profondeur_max_enracinement_classe",
	),
	solProfondeurMaxEnracinement: doublePrecision(
		"sol_profondeur_max_enracinement",
	),
	teneurMoPct: doublePrecision("teneur_mo_pct"),
	hydromorphie: boolean("hydromorphie"),
	calcaire: boolean("calcaire"),
	proportionCalcaireTotal: doublePrecision("proportion_calcaire_total"),
	proportionCalcaireActif: doublePrecision("proportion_calcaire_actif"),
	battance: boolean("battance"),
	domaineId: text("domaine_id"),
	sdcId: text("sdc_id"),
	domaineSolId: text("domaine_sol_id"),
});

export type Parcelle = typeof parcelle.$inferSelect;
export type NewParcelle = typeof parcelle.$inferInsert;
