import { pgTable, text, integer, doublePrecision, boolean } from "drizzle-orm/pg-core";
import { dispositif } from "./dispositif";

export const sdc = pgTable("sdc", {
	id: text("id").primaryKey(),
	filiere: text("filiere"),
	typeAgriculture: text("type_agriculture"),
	partSauDomaine: doublePrecision("part_sau_domaine"),
	partMoDomaine: doublePrecision("part_mo_domaine"),
	partMaterielDomaine: doublePrecision("part_materiel_domaine"),
	cipan: boolean("cipan"),
	varPeuSensiblesMaladies: boolean("var_peu_sensibles_maladies"),
	broyageBordure: boolean("broyage_bordure"),
	gestionBordureDeBois: boolean("gestion_bordure_de_bois"),
	codeDephy: text("code_dephy"),
	codesConventionDephy: text("codes_convention_dephy"),
	commentaire: text("commentaire"),
	couvertsAssocies: boolean("couverts_associes"),
	culturesPieges: boolean("cultures_pieges"),
	decompactageFrequent: boolean("decompactage_frequent"),
	decompactageOccasionnel: boolean("decompactage_occasionnel"),
	desherbageAutreForm: boolean("desherbage_autre_forme"),
	desherbageMecaFrequent: boolean("desherbage_meca_frequent"),
	desherbageMecaOccasionnel: boolean("desherbage_meca_occasionnel"),
	desherbageThermique: boolean("desherbage_thermique"),
	destructionLitiere: boolean("destruction_litiere"),
	doseAdapteeSurfFoliaire: boolean("dose_adaptee_surf_foliaire"),
	enherbementNaturel: boolean("enherbement_naturel"),
	enherbementSeme: boolean("enherbement_seme"),
	exportationMenuPailles: boolean("exportation_menu_pailles"),
	faibleDensite: boolean("faible_densite"),
	faibleEcartement: boolean("faible_ecartement"),
	fauxSemisIntensifs: boolean("faux_semis_intensifs"),
	fauxSemisPonctuels: boolean("faux_semis_ponctuels"),
	filetAntiInsectes: boolean("filet_anti_insectes"),
	fortEcartement: boolean("fort_ecartement"),
	forteDensite: boolean("forte_densite"),
	gestionResidus: boolean("gestion_residus"),
	haiesAnciennes: boolean("haies_anciennes"),
	haiesJeunes: boolean("haies_jeunes"),
	labourFrequent: boolean("labour_frequent"),
	labourOccasionnel: boolean("labour_occasionnel"),
	labourSystematique: boolean("labour_systematique"),
	lutteBioAutre: boolean("lutte_bio_autre"),
	lutteBioConfuSexuelle: boolean("lutte_bio_confu_sexuelle"),
	melange: boolean("melange"),
	modaliteSuiviDephy: text("modalite_suivi_dephy"),
	modesCommercialisation: text("modes_commercialisation"),
	monocultureRotationCourte: boolean("monoculture_rotation_courte"),
	optimConditionsApplication: boolean("optim_conditions_application"),
	reductionDoseAutresPhyto: boolean("reduction_dose_autres_phyto"),
	reductionDoseFongi: boolean("reduction_dose_fongi"),
	reductionDoseHerbi: boolean("reduction_dose_herbi"),
	reductionDoseInsec: boolean("reduction_dose_insec"),
	rotationCulturesRustiques: boolean("rotation_cultures_rustiques"),
	rotationDiversifieAvecPt: boolean("rotation_diversifiee_avec_pt"),
	rotationDiversifieeIntroUneCulture: boolean("rotation_diversifiee_intro_une_culture"),
	rotationDiversifieeSansPt: boolean("rotation_diversifiee_sans_pt"),
	adaptationLutteALaParcelle: boolean("adaptation_lutte_a_la_parcelle"),
	semiDirectSystematique: boolean("semis_direct_systematique"),
	semisPrecoce: boolean("semis_precoce"),
	semisTardif: boolean("semis_tardif"),
	strategieCategorie: text("strategie_categorie"),
	stripTillFrequent: boolean("strip_till_frequent"),
	stripTillOccasionnel: boolean("strip_till_occasionnel"),
	tailleLimitantRisquesSanitaires: boolean("taille_limitant_risques_sanitaires"),
	tailleOrganesContamines: boolean("taille_organes_contamines"),
	tcs: boolean("tcs"),
	traitementLocalise: boolean("traitement_localise"),
	typeProduction: text("type_production"),
	varPeuSensiblesVerse: boolean("var_peu_sensibles_verse"),
	utilisationAdjuvants: boolean("utilisation_adjuvants"),
	utilisationOad: boolean("utilisation_oad"),
	utilisationSeuils: boolean("utilisation_seuils"),
	utilisationStimDefense: boolean("utilisation_stim_defense"),
	validite: boolean("validite"),
	varCompetitivesAdventic: boolean("var_competitives_adventice"),
	varPeuSensiblesRavageurs: boolean("var_peu_sensibles_ravageurs"),
	semiDirectOccasionnel: boolean("semis_direct_occasionnel"),
	agroforesterie: boolean("agroforesterie"),
	ajustementFertilisation: boolean("ajustement_fertilisation"),
	ajustementIrrigation: boolean("ajustement_irrigation"),
	arbresBordureParcelle: boolean("arbres_bordure_parcelle"),
	bandesEnherbees: boolean("bandes_enherbees"),
	bandesFleuries: boolean("bandes_fleuries"),
	boisBosquet: boolean("bois_bosquet"),
	campagne: integer("campagne").notNull(),
	ciAttractivesPourAuxiliaires: boolean("ci_attractives_pour_auxiliaires"),
	ciEffetAlleloOuBiocide: boolean("ci_effet_allelo_ou_biocide"),
	code: text("code").notNull(),
	dispositifId: text("dispositif_id")
		.notNull()
		.references(() => dispositif.id),
});

export type Sdc = typeof sdc.$inferSelect;
export type NewSdc = typeof sdc.$inferInsert;
