import { pgTable, text, doublePrecision, boolean, integer } from "drizzle-orm/pg-core";
import { sdc } from "../contexte/sdc";
import { dispositif } from "../contexte/dispositif";

export const synthetisePerfMagasinCan = pgTable("synthetise_perf_magasin_can", {
  systemeSynthetiseId: text("systeme_synthetise_id")
    .primaryKey(),

  synthetiseValide: boolean("synthetise_valide"),
  synthetiseCampagnes: text("synthetise_campagnes"),

  // IFT historique
  iftHistoChimiqueTot: doublePrecision("ift_histo_chimique_tot"),
  iftHistoChimTotHts: doublePrecision("ift_histo_chim_tot_hts"),
  iftHistoH: doublePrecision("ift_histo_h"),
  iftHistoF: doublePrecision("ift_histo_f"),
  iftHistoI: doublePrecision("ift_histo_i"),
  iftHistoTs: doublePrecision("ift_histo_ts"),
  iftHistoA: doublePrecision("ift_histo_a"),
  iftHistoHh: doublePrecision("ift_histo_hh"),
  iftHistoBiocontrole: doublePrecision("ift_histo_biocontrole"),
  iftHistoTxComp: doublePrecision("ift_histo_tx_comp"),

  // Temps utilisation matériel
  tpsUtilisationMaterielJanvier: doublePrecision("tps_utilisation_materiel_janvier"),
  tpsUtilisationMaterielFevrier: doublePrecision("tps_utilisation_materiel_fevrier"),
  tpsUtilisationMaterielMars: doublePrecision("tps_utilisation_materiel_mars"),
  tpsUtilisationMaterielAvril: doublePrecision("tps_utilisation_materiel_avril"),
  tpsUtilisationMaterielMai: doublePrecision("tps_utilisation_materiel_mai"),
  tpsUtilisationMaterielJuin: doublePrecision("tps_utilisation_materiel_juin"),
  tpsUtilisationMaterielJuillet: doublePrecision("tps_utilisation_materiel_juillet"),
  tpsUtilisationMaterielAout: doublePrecision("tps_utilisation_materiel_aout"),
  tpsUtilisationMaterielSept: doublePrecision("tps_utilisation_materiel_sept"),
  tpsUtilisationMaterielOct: doublePrecision("tps_utilisation_materiel_oct"),
  tpsUtilisationMaterielNov: doublePrecision("tps_utilisation_materiel_nov"),
  tpsUtilisationMaterielDec: doublePrecision("tps_utilisation_materiel_dec"),
  tpsUtilisationMateriel: doublePrecision("tps_utilisation_materiel"),
  tpsUtilisationMaterielTxComp: doublePrecision("tps_utilisation_materiel_tx_comp"),

  // IFT cible non mil
  iftCibleNonMilChimiqueTot: doublePrecision("ift_cible_non_mil_chimique_tot"),
  iftCibleNonMilChimTotHts: doublePrecision("ift_cible_non_mil_chim_tot_hts"),
  iftCibleNonMilH: doublePrecision("ift_cible_non_mil_h"),
  iftCibleNonMilF: doublePrecision("ift_cible_non_mil_f"),
  iftCibleNonMilI: doublePrecision("ift_cible_non_mil_i"),
  iftCibleNonMilTs: doublePrecision("ift_cible_non_mil_ts"),
  iftCibleNonMilA: doublePrecision("ift_cible_non_mil_a"),
  iftCibleNonMilHh: doublePrecision("ift_cible_non_mil_hh"),
  iftCibleNonMilBiocontrole: doublePrecision("ift_cible_non_mil_biocontrole"),
  iftCibleNonMilTxComp: doublePrecision("ift_cible_non_mil_tx_comp"),

  // Temps travail manuel
  tpsTravailManuelJanvier: doublePrecision("tps_travail_manuel_janvier"),
  tpsTravailManuelFevrier: doublePrecision("tps_travail_manuel_fevrier"),
  tpsTravailManuelMars: doublePrecision("tps_travail_manuel_mars"),
  tpsTravailManuelAvril: doublePrecision("tps_travail_manuel_avril"),
  tpsTravailManuelMai: doublePrecision("tps_travail_manuel_mai"),
  tpsTravailManuelJuin: doublePrecision("tps_travail_manuel_juin"),
  tpsTravailManuelJuillet: doublePrecision("tps_travail_manuel_juillet"),
  tpsTravailManuelAout: doublePrecision("tps_travail_manuel_aout"),
  tpsTravailManuelSeptembre: doublePrecision("tps_travail_manuel_septembre"),
  tpsTravailManuelOctobre: doublePrecision("tps_travail_manuel_octobre"),
  tpsTravailManuelNovembre: doublePrecision("tps_travail_manuel_novembre"),
  tpsTravailManuelDecembre: doublePrecision("tps_travail_manuel_decembre"),
  tpsTravailManuel: doublePrecision("tps_travail_manuel"),
  tpsTravailManuelTxComp: doublePrecision("tps_travail_manuel_tx_comp"),

  // IFT cible mil
  iftCibleMilChimiqueTot: doublePrecision("ift_cible_mil_chimique_tot"),
  iftCibleMilChimTotHts: doublePrecision("ift_cible_mil_chim_tot_hts"),
  iftCibleMilH: doublePrecision("ift_cible_mil_h"),
  iftCibleMilF: doublePrecision("ift_cible_mil_f"),
  iftCibleMilI: doublePrecision("ift_cible_mil_i"),
  iftCibleMilTs: doublePrecision("ift_cible_mil_ts"),
  iftCibleMilA: doublePrecision("ift_cible_mil_a"),
  iftCibleMilHh: doublePrecision("ift_cible_mil_hh"),
  iftCibleMilBiocontrole: doublePrecision("ift_cible_mil_biocontrole"),
  iftCibleMilTxComp: doublePrecision("ift_cible_mil_tx_comp"),

  // Temps travail mécanisé
  tpsTravailMecaniseJanvier: doublePrecision("tps_travail_mecanise_janvier"),
  tpsTravailMecaniseFevrier: doublePrecision("tps_travail_mecanise_fevrier"),
  tpsTravailMecaniseMars: doublePrecision("tps_travail_mecanise_mars"),
  tpsTravailMecaniseAvril: doublePrecision("tps_travail_mecanise_avril"),
  tpsTravailMecaniseMai: doublePrecision("tps_travail_mecanise_mai"),
  tpsTravailMecaniseJuin: doublePrecision("tps_travail_mecanise_juin"),
  tpsTravailMecaniseJuillet: doublePrecision("tps_travail_mecanise_juillet"),
  tpsTravailMecaniseAout: doublePrecision("tps_travail_mecanise_aout"),
  tpsTravailMecaniseSeptembre: doublePrecision("tps_travail_mecanise_septembre"),
  tpsTravailMecaniseOctobre: doublePrecision("tps_travail_mecanise_octobre"),
  tpsTravailMecaniseNovembre: doublePrecision("tps_travail_mecanise_novembre"),
  tpsTravailMecaniseDecembre: doublePrecision("tps_travail_mecanise_decembre"),
  tpsTravailMecanise: doublePrecision("tps_travail_mecanise"),
  tpsTravailMecaniseTxComp: doublePrecision("tps_travail_mecanise_tx_comp"),

  // IFT culture non mil
  iftCultureNonMilChimiqueTot: doublePrecision("ift_culture_non_mil_chimique_tot"),
  iftCultureNonMilChimTotHts: doublePrecision("ift_culture_non_mil_chim_tot_hts"),
  iftCultureNonMilH: doublePrecision("ift_culture_non_mil_h"),
  iftCultureNonMilF: doublePrecision("ift_culture_non_mil_f"),
  iftCultureNonMilI: doublePrecision("ift_culture_non_mil_i"),
  iftCultureNonMilTs: doublePrecision("ift_culture_non_mil_ts"),
  iftCultureNonMilA: doublePrecision("ift_culture_non_mil_a"),
  iftCultureNonMilHh: doublePrecision("ift_culture_non_mil_hh"),
  iftCultureNonMilBiocontrole: doublePrecision("ift_culture_non_mil_biocontrole"),
  iftCultureNonMilTxComp: doublePrecision("ift_culture_non_mil_tx_comp"),

  // Temps travail total
  tpsTravailTotalJanvier: doublePrecision("tps_travail_total_janvier"),
  tpsTravailTotalFevrier: doublePrecision("tps_travail_total_fevrier"),
  tpsTravailTotalMars: doublePrecision("tps_travail_total_mars"),
  tpsTravailTotalAvril: doublePrecision("tps_travail_total_avril"),
  tpsTravailTotalMai: doublePrecision("tps_travail_total_mai"),
  tpsTravailTotalJuin: doublePrecision("tps_travail_total_juin"),
  tpsTravailTotalJuillet: doublePrecision("tps_travail_total_juillet"),
  tpsTravailTotalAout: doublePrecision("tps_travail_total_aout"),
  tpsTravailTotalSeptembre: doublePrecision("tps_travail_total_septembre"),
  tpsTravailTotalOctobre: doublePrecision("tps_travail_total_octobre"),
  tpsTravailTotalNovembre: doublePrecision("tps_travail_total_novembre"),
  tpsTravailTotalDecembre: doublePrecision("tps_travail_total_decembre"),
  tpsTravailTotal: doublePrecision("tps_travail_total"),
  tpsTravailTotalTxComp: doublePrecision("tps_travail_total_tx_comp"),

  // IFT culture mil
  iftCultureMilChimiqueTot: doublePrecision("ift_culture_mil_chimique_tot"),
  iftCultureMilChimTotHts: doublePrecision("ift_culture_mil_chim_tot_hts"),
  iftCultureMilH: doublePrecision("ift_culture_mil_h"),
  iftCultureMilF: doublePrecision("ift_culture_mil_f"),
  iftCultureMilI: doublePrecision("ift_culture_mil_i"),
  iftCultureMilTs: doublePrecision("ift_culture_mil_ts"),
  iftCultureMilA: doublePrecision("ift_culture_mil_a"),
  iftCultureMilHh: doublePrecision("ift_culture_mil_hh"),
  iftCultureMilBiocontrole: doublePrecision("ift_culture_mil_biocontrole"),
  iftCultureMilTxComp: doublePrecision("ift_culture_mil_tx_comp"),

  // Nombre de passages
  nbreDePassagesJanvier: doublePrecision("nbre_de_passages_janvier"),
  nbreDePassagesFevrier: doublePrecision("nbre_de_passages_fevrier"),
  nbreDePassagesMars: doublePrecision("nbre_de_passages_mars"),
  nbreDePassagesAvril: doublePrecision("nbre_de_passages_avril"),
  nbreDePassagesMai: doublePrecision("nbre_de_passages_mai"),
  nbreDePassagesJuin: doublePrecision("nbre_de_passages_juin"),
  nbreDePassagesJuillet: doublePrecision("nbre_de_passages_juillet"),
  nbreDePassagesAout: doublePrecision("nbre_de_passages_aout"),
  nbreDePassagesSeptembre: doublePrecision("nbre_de_passages_septembre"),
  nbreDePassagesOctobre: doublePrecision("nbre_de_passages_octobre"),
  nbreDePassagesNovembre: doublePrecision("nbre_de_passages_novembre"),
  nbreDePassagesDecembre: doublePrecision("nbre_de_passages_decembre"),
  nbreDePassages: doublePrecision("nbre_de_passages"),
  nbreDePassagesTxComp: doublePrecision("nbre_de_passages_tx_comp"),
  nbreDePassagesLabour: doublePrecision("nbre_de_passages_labour"),
  nbreDePassagesLabourTxComp: doublePrecision("nbre_de_passages_labour_tx_comp"),
  nbreDePassagesTcs: doublePrecision("nbre_de_passages_tcs"),
  nbreDePassagesTcsTxComp: doublePrecision("nbre_de_passages_tcs_tx_comp"),
  nbreDePassagesDesherbage_meca: doublePrecision("nbre_de_passages_desherbage_meca"),
  nbreDePassagesDesherbageMecaTxComp: doublePrecision("nbre_de_passages_desherbage_meca_tx_comp"),

  // Recours biologiques
  recoursAuxMoyensBiologiques: doublePrecision("recours_aux_moyens_biologiques"),
  recoursMacroorganismes: doublePrecision("recours_macroorganismes"),
  recoursProduitsBiotiquesSansamm: doublePrecision("recours_produits_biotiques_sansamm"),
  recoursProduitsAbiotiquesSansamm: doublePrecision("recours_produits_abiotiques_sansamm"),

  // Coûts totaux réels
  coTotReelles: doublePrecision("co_tot_reelles"),
  coTotReellesTxComp: doublePrecision("co_tot_reelles_tx_comp"),
  coTotStdMil: doublePrecision("co_tot_std_mil"),
  coTotStdMilTxComp: doublePrecision("co_tot_std_mil_tx_comp"),

  // Décomposition des coûts
  coSemisReel: doublePrecision("co_semis_reel"),
  coSemisStdMil: doublePrecision("co_semis_std_mil"),
  coFertaminReel: doublePrecision("co_fertimin_reel"),
  coFertaminStdMil: doublePrecision("co_fertimin_std_mil"),
  coEpandageOrgaReelles: doublePrecision("co_epandage_orga_reelles"),
  coEpandageOrgaStdMil: doublePrecision("co_epandage_orga_std_mil"),
  coPhytoSansAmmReelles: doublePrecision("co_phyto_sans_amm_reelles"),
  coPhytoSansAmmStdMil: doublePrecision("co_phyto_sans_amm_std_mil"),
  coPhytoAvecAmmReelles: doublePrecision("co_phyto_avec_amm_reelles"),
  coPhytoAvecAmmStdMil: doublePrecision("co_phyto_avec_amm_std_mil"),
  coTraitSemenceReelles: doublePrecision("co_trait_semence_reelles"),
  coTraitSemenceStdMil: doublePrecision("co_trait_semence_std_mil"),
  coIrrigationReelles: doublePrecision("co_irrigation_reelles"),
  coIrrigationStdMil: doublePrecision("co_irrigation_std_mil"),
  coSubstratsReelles: doublePrecision("co_substrats_reelles"),
  coSubstratsStdMil: doublePrecision("co_substrats_std_mil"),
  coPotsReelles: doublePrecision("co_pots_reelles"),
  coPotsStdMil: doublePrecision("co_pots_std_mil"),
  coIntrantsAutresReelles: doublePrecision("co_intrants_autres_reelles"),
  coIntrantsAutresStdMil: doublePrecision("co_intrants_autres_std_mil"),
  coDecomposeeReelTxComp: doublePrecision("co_decomposees_reel_tx_comp"),
  coDecomposeeStdMilTxComp: doublePrecision("co_decomposees_std_mil_tx_comp"),

  // Utilisation désherbage méca
  utiliDesherbageMeca: doublePrecision("utili_desherbage_meca"),
  utiliDesherbageMecaTxComp: doublePrecision("utili_desherbage_meca_tx_comp"),

  // Type de travail du sol
  typeDeTravailDuSol: text("type_de_travail_du_sol"),
  typeDeTravailDuSolTxComp: doublePrecision("type_de_travail_du_sol_tx_comp"),

  // Charges matériel
  cmReelles: doublePrecision("cm_reelles"),
  cmReellesTxComp: doublePrecision("cm_reelles_tx_comp"),
  cmStdMil: doublePrecision("cm_std_mil"),
  cmStdMilTxComp: doublePrecision("cm_std_mil_tx_comp"),

  // Main d'oeuvre
  cMainOeuvreTotReelle: doublePrecision("c_main_oeuvre_tot_reelle"),
  cMainOeuvreTotReelleTxComp: doublePrecision("c_main_oeuvre_tot_reelle_tx_comp"),
  cMainOeuvreTotStdMil: doublePrecision("c_main_oeuvre_tot_std_mil"),
  cMainOeuvreTotStdMilTxComp: doublePrecision("c_main_oeuvre_tot_std_mil_tx_comp"),
  cMainOeuvreTractoristeReelle: doublePrecision("c_main_oeuvre_tractoriste_reelle"),
  cMainOeuvreTractoristeReelleTxComp: doublePrecision("c_main_oeuvre_tractoriste_reelle_tx_comp"),
  cMainOeuvreTractoristeStdMil: doublePrecision("c_main_oeuvre_tractoriste_std_mil"),
  cMainOeuvreTractoristeStdMilTxComp: doublePrecision("c_main_oeuvre_tractoriste_std_mil_tx_comp"),
  cMainOeuvreManuelleReelle: doublePrecision("c_main_oeuvre_manuelle_reelle"),
  cMainOeuvreManuelleReelleTxComp: doublePrecision("c_main_oeuvre_manuelle_reelle_tx_comp"),
  cMainOeuvreManuelleStdMil: doublePrecision("c_main_oeuvre_manuelle_std_mil"),
  cMainOeuvreManuelleStdMilTxComp: doublePrecision("c_main_oeuvre_manuelle_std_mil_tx_comp"),

  // Fertilisation
  fertiNTot: doublePrecision("ferti_n_tot"),
  fertiNMineral: doublePrecision("ferti_n_mineral"),
  fertiNOrganique: doublePrecision("ferti_n_organique"),
  fertiP2o5Tot: doublePrecision("ferti_p2o5_tot"),
  fertiP2o5Mineral: doublePrecision("ferti_p2o5_mineral"),
  fertiP2o5Organique: doublePrecision("ferti_p2o5_organique"),
  fertiK2oTot: doublePrecision("ferti_k2o_tot"),
  fertiK2oMineral: doublePrecision("ferti_k2o_mineral"),
  fertiK2oOrganique: doublePrecision("ferti_k2o_organique"),
  fertiCaMineral: doublePrecision("ferti_ca_mineral"),
  fertiCaoOrganique: doublePrecision("ferti_cao_organique"),
  fertiMgoMineral: doublePrecision("ferti_mgo_mineral"),
  fertiMgoOrganique: doublePrecision("ferti_mgo_organique"),
  fertiSo3Mineral: doublePrecision("ferti_so3_mineral"),
  fertiSOrganique: doublePrecision("ferti_s_organique"),
  fertiBMineral: doublePrecision("ferti_b_mineral"),
  fertiCuMineral: doublePrecision("ferti_cu_mineral"),
  fertiFeMineral: doublePrecision("ferti_fe_mineral"),
  fertiMnMineral: doublePrecision("ferti_mn_mineral"),
  fertiMoMineral: doublePrecision("ferti_mo_mineral"),
  fertiNa2oMineral: doublePrecision("ferti_na2o_mineral"),
  fertiZnMineral: doublePrecision("ferti_zn_mineral"),

  // Produit brut
  pbReelSansAutoconso: doublePrecision("pb_reel_sans_autoconso"),
  pbReelAvecAutoconso: doublePrecision("pb_reel_avec_autoconso"),
  pbReelTxComp: doublePrecision("pb_reel_tx_comp"),
  pbStdMilAvecAutoconso: doublePrecision("pb_std_mil_avec_autoconso"),
  pbStdMilSansAutoconso: doublePrecision("pb_std_mil_sans_autoconso"),
  pbStdMilTxComp: doublePrecision("pb_std_mil_tx_comp"),

  // Marge brute
  mbReelleSansAutoconso: doublePrecision("mb_reelle_sans_autoconso"),
  mbReelleAvecAutoconso: doublePrecision("mb_reelle_avec_autoconso"),
  mbReelleTxComp: doublePrecision("mb_reelle_tx_comp"),
  mbStdMilAvecAutoconso: doublePrecision("mb_std_mil_avec_autoconso"),
  mbStdMilSansAutoconso: doublePrecision("mb_std_mil_sans_autoconso"),
  mbStdMilTxComp: doublePrecision("mb_std_mil_tx_comp"),

  // Marge semi-nette
  msnReelleSansAutoconso: doublePrecision("msn_reelle_sans_autoconso"),
  msnReelleAvecAutoconso: doublePrecision("msn_reelle_avec_autoconso"),
  msnReelleTxComp: doublePrecision("msn_reelle_tx_comp"),
  msnStdMilSansAutoconso: doublePrecision("msn_std_mil_sans_autoconso"),
  msnStdMilAvecAutoconso: doublePrecision("msn_std_mil_avec_autoconso"),
  msnStdMilTxComp: doublePrecision("msn_std_mil_tx_comp"),

  // Marge directe
  mdReelleSansAutoconso: doublePrecision("md_reelle_sans_autoconso"),
  mdReelleAvecAutoconso: doublePrecision("md_reelle_avec_autoconso"),
  mdReelleTxComp: doublePrecision("md_reelle_tx_comp"),
  mdStdMilSansAutoconso: doublePrecision("md_std_mil_sans_autoconso"),
  mdStdMilAvecAutoconso: doublePrecision("md_std_mil_avec_autoconso"),
  mdStdMilTxComp: doublePrecision("md_std_mil_tx_comp"),

  // HRI1
  hri1Tot: doublePrecision("hri1_tot"),
  hri1Hts: doublePrecision("hri1_hts"),
  hri1TotTauxDeCompletion: doublePrecision("hri1_tot_taux_de_completion"),
  hri1G1Tot: doublePrecision("hri1_g1_tot"),
  hri1G1Hts: doublePrecision("hri1_g1_hts"),
  hri1G1TotTauxDeCompletion: doublePrecision("hri1_g1_tot_taux_de_completion"),
  hri1G2Tot: doublePrecision("hri1_g2_tot"),
  hri1G2Hts: doublePrecision("hri1_g2_hts"),
  hri1G2TotTauxDeCompletion: doublePrecision("hri1_g2_tot_taux_de_completion"),
  hri1G3Tot: doublePrecision("hri1_g3_tot"),
  hri1G3Hts: doublePrecision("hri1_g3_hts"),
  hri1G3TotTauxDeCompletion: doublePrecision("hri1_g3_tot_taux_de_completion"),
  hri1G4Tot: doublePrecision("hri1_g4_tot"),
  hri1G4Hts: doublePrecision("hri1_g4_hts"),
  hri1G4TotTauxDeCompletion: doublePrecision("hri1_g4_tot_taux_de_completion"),

  // QSA
  qsaTot: doublePrecision("qsa_tot"),
  qsaTotHts: doublePrecision("qsa_tot_hts"),
  qsaTotTauxDeCompletion: doublePrecision("qsa_tot_taux_de_completion"),
  qsaDangerEnvironnement: doublePrecision("qsa_danger_environnement"),
  qsaDangerEnvironnementHts: doublePrecision("qsa_danger_environnement_hts"),
  qsaToxiqueUtilisateur: doublePrecision("qsa_toxique_utilisateur"),
  qsaToxiqueUtilisateurHts: doublePrecision("qsa_toxique_utilisateur_hts"),
  qsaCmr: doublePrecision("qsa_cmr"),
  qsaCmrHts: doublePrecision("qsa_cmr_hts"),
  qsaSubstancesCandidatesSubstitution: doublePrecision("qsa_substances_candidates_substitution"),
  qsaSubstancesCandidatesSubstitutionHts: doublePrecision("qsa_substances_candidates_substitution_hts"),
  qsaSubstancesFaibleRisque: doublePrecision("qsa_substances_faible_risque"),
  qsaSubstancesFaibleRisqueHts: doublePrecision("qsa_substances_faible_risque_hts"),
  qsaGlyphosate: doublePrecision("qsa_glyphosate"),
  qsaGlyphosateHts: doublePrecision("qsa_glyphosate_hts"),
  qsaChlortoluron: doublePrecision("qsa_chlortoluron"),
  qsaChlortoluronHts: doublePrecision("qsa_chlortoluron_hts"),
  qsaDiflufenican: doublePrecision("qsa_diflufenican"),
  qsaDiflufenicaHts: doublePrecision("qsa_diflufenican_hts"),
  qsaProsulfocarbe: doublePrecision("qsa_prosulfocarbe"),
  qsaProsulfocarbelHts: doublePrecision("qsa_prosulfocarbe_hts"),
  qsaSmetolachlore: doublePrecision("qsa_smetolachlore"),
  qsaSmetolachloreHts: doublePrecision("qsa_smetolachlore_hts"),
  qsaBoscalid: doublePrecision("qsa_boscalid"),
  qsaBoscalidHts: doublePrecision("qsa_boscalid_hts"),
  qsaFluopyram: doublePrecision("qsa_fluopyram"),
  qsaFluopyramHts: doublePrecision("qsa_fluopyram_hts"),
  qsaLambdaCyhalothrine: doublePrecision("qsa_lambda_cyhalothrine"),
  qsaLambdaCyhalothrineHts: doublePrecision("qsa_lambda_cyhalothrine_hts"),
  qsaCuivreTot: doublePrecision("qsa_cuivre_tot"),
  qsaCuivreTotHts: doublePrecision("qsa_cuivre_tot_hts"),
  qsaCuivrePhyto: doublePrecision("qsa_cuivre_phyto"),
  qsaCuivrePhytoHts: doublePrecision("qsa_cuivre_phyto_hts"),
  qsaCuivreFerti: doublePrecision("qsa_cuivre_ferti"),
  qsaSoufreTot: doublePrecision("qsa_soufre_tot"),
  qsaSoufreTotHts: doublePrecision("qsa_soufre_tot_hts"),
  qsaSoufrePhyto: doublePrecision("qsa_soufre_phyto"),
  qsaSoufrePhytoHts: doublePrecision("qsa_soufre_phyto_hts"),
  qsaSoufretFerti: doublePrecision("qsa_soufre_ferti"),

  // Surface, carburant, eau
  surfUniteDeWHumain: doublePrecision("surf_unite_de_w_humain"),
  surfUniteDeWHumainTxComp: doublePrecision("surf_unite_de_w_humain_tx_comp"),
  consoCarburant: doublePrecision("conso_carburant"),
  consoCarburantTxComp: doublePrecision("conso_carburant_tx_comp"),
  consoEau: doublePrecision("conso_eau"),
  consoEauTxComp: doublePrecision("conso_eau_tx_comp"),
  nombreUthNecessaires: doublePrecision("nombre_uth_necessaires"),

  // Metadata - Domaine / Dispositif
  domaineNom: text("domaine_nom"),
  domaineId: text("domaine_id"),
  domaineCampagne: integer("domaine_campagne"),
  domaineType: text("domaine_type"),
  departement: text("departement"),
  dispositifId: text("dispositif_id").references(() => dispositif.id),
  dispositifType: text("dispositif_type"),
  sdcFiliere: text("sdc_filiere"),
  sdcNom: text("sdc_nom"),
  sdcCodeDephy: text("sdc_code_dephy"),
  sdcTypeAgriculture: text("sdc_type_agriculture"),
  sdcValide: boolean("sdc_valide"),
  sdcId: text("sdc_id").references(() => sdc.id),
});

export type SynthetisePerfMagasinCan = typeof synthetisePerfMagasinCan.$inferSelect;
export type NewSynthetisePerfMagasinCan = typeof synthetisePerfMagasinCan.$inferInsert;
